### ISSUE TITLE
RFE: Support image inside progress bar.

### ISSUE THREAD

**Issue by kents1** [appreciated/circular-progressbar#1]
This is a great component.  As an idea for an feature, it would be great to have the ability to pass an image to be displayed inside the progress bar, below the percentage text.

Image would be scaled to fit dimensions and masked to be circular to fit.

Would be great if you could consider this.

Thanks.

**Comment by appreciated** [comment]
You can do this already either quick and dirty via CSS but this wouldn't be a dynamic solution.
I won't add a method to the CircularProgressbar Extension itself, since this is a JavaScriptExtension and I think it would be rather complicated to pass the image / icon it that way to the client and parse it there. 

Way easier and also dynamic should do the job (note the order in the layout)
- com.vaadin.ui.AbsoluteLayout (Fixed Size)
  - com.vaadin.ui.Image (Full Width, Customized with CSS to be round)
  - CircularProgressbar (Full Width)
 ````
  .round-image {
      border-radius: 100%;
      ...
  }
  ````

I think I'll add a ImageCircularProgressbar Variation which does exactly that. For now I suggest you can create your own Variant

**Comment by appreciated** [comment]
Give me please some feedback based on Version 0.8
